//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cPos.Admin.Task.MonitorLogServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MonitorLogInfo", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class MonitorLogInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string monitor_log_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string customer_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string unit_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string pos_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string upload_timeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string remarkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string create_timeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string create_user_idField;
        
        private int if_flagField;
        
        private int icountField;
        
        private int row_noField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string bat_idField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string monitor_log_id {
            get {
                return this.monitor_log_idField;
            }
            set {
                if ((object.ReferenceEquals(this.monitor_log_idField, value) != true)) {
                    this.monitor_log_idField = value;
                    this.RaisePropertyChanged("monitor_log_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string customer_id {
            get {
                return this.customer_idField;
            }
            set {
                if ((object.ReferenceEquals(this.customer_idField, value) != true)) {
                    this.customer_idField = value;
                    this.RaisePropertyChanged("customer_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string unit_id {
            get {
                return this.unit_idField;
            }
            set {
                if ((object.ReferenceEquals(this.unit_idField, value) != true)) {
                    this.unit_idField = value;
                    this.RaisePropertyChanged("unit_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string pos_id {
            get {
                return this.pos_idField;
            }
            set {
                if ((object.ReferenceEquals(this.pos_idField, value) != true)) {
                    this.pos_idField = value;
                    this.RaisePropertyChanged("pos_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string upload_time {
            get {
                return this.upload_timeField;
            }
            set {
                if ((object.ReferenceEquals(this.upload_timeField, value) != true)) {
                    this.upload_timeField = value;
                    this.RaisePropertyChanged("upload_time");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string remark {
            get {
                return this.remarkField;
            }
            set {
                if ((object.ReferenceEquals(this.remarkField, value) != true)) {
                    this.remarkField = value;
                    this.RaisePropertyChanged("remark");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string create_time {
            get {
                return this.create_timeField;
            }
            set {
                if ((object.ReferenceEquals(this.create_timeField, value) != true)) {
                    this.create_timeField = value;
                    this.RaisePropertyChanged("create_time");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string create_user_id {
            get {
                return this.create_user_idField;
            }
            set {
                if ((object.ReferenceEquals(this.create_user_idField, value) != true)) {
                    this.create_user_idField = value;
                    this.RaisePropertyChanged("create_user_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public int if_flag {
            get {
                return this.if_flagField;
            }
            set {
                if ((this.if_flagField.Equals(value) != true)) {
                    this.if_flagField = value;
                    this.RaisePropertyChanged("if_flag");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public int icount {
            get {
                return this.icountField;
            }
            set {
                if ((this.icountField.Equals(value) != true)) {
                    this.icountField = value;
                    this.RaisePropertyChanged("icount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public int row_no {
            get {
                return this.row_noField;
            }
            set {
                if ((this.row_noField.Equals(value) != true)) {
                    this.row_noField = value;
                    this.RaisePropertyChanged("row_no");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string bat_id {
            get {
                return this.bat_idField;
            }
            set {
                if ((object.ReferenceEquals(this.bat_idField, value) != true)) {
                    this.bat_idField = value;
                    this.RaisePropertyChanged("bat_id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MonitorLogServiceReference.MonitorLogWebServiceSoap")]
    public interface MonitorLogWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        cPos.Admin.Task.MonitorLogServiceReference.HelloWorldResponse HelloWorld(cPos.Admin.Task.MonitorLogServiceReference.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name Customer_Id from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMonitorLogNotPackagedCount", ReplyAction="*")]
        cPos.Admin.Task.MonitorLogServiceReference.GetMonitorLogNotPackagedCountResponse GetMonitorLogNotPackagedCount(cPos.Admin.Task.MonitorLogServiceReference.GetMonitorLogNotPackagedCountRequest request);
        
        // CODEGEN: Generating message contract since element name Customer_Id from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMonitorLogListPackaged", ReplyAction="*")]
        cPos.Admin.Task.MonitorLogServiceReference.GetMonitorLogListPackagedResponse GetMonitorLogListPackaged(cPos.Admin.Task.MonitorLogServiceReference.GetMonitorLogListPackagedRequest request);
        
        // CODEGEN: Generating message contract since element name Customer_Id from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SetMonitorLogIfFlagInfo", ReplyAction="*")]
        cPos.Admin.Task.MonitorLogServiceReference.SetMonitorLogIfFlagInfoResponse SetMonitorLogIfFlagInfo(cPos.Admin.Task.MonitorLogServiceReference.SetMonitorLogIfFlagInfoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public cPos.Admin.Task.MonitorLogServiceReference.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(cPos.Admin.Task.MonitorLogServiceReference.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public cPos.Admin.Task.MonitorLogServiceReference.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(cPos.Admin.Task.MonitorLogServiceReference.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMonitorLogNotPackagedCountRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMonitorLogNotPackagedCount", Namespace="http://tempuri.org/", Order=0)]
        public cPos.Admin.Task.MonitorLogServiceReference.GetMonitorLogNotPackagedCountRequestBody Body;
        
        public GetMonitorLogNotPackagedCountRequest() {
        }
        
        public GetMonitorLogNotPackagedCountRequest(cPos.Admin.Task.MonitorLogServiceReference.GetMonitorLogNotPackagedCountRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetMonitorLogNotPackagedCountRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Customer_Id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Unit_Id;
        
        public GetMonitorLogNotPackagedCountRequestBody() {
        }
        
        public GetMonitorLogNotPackagedCountRequestBody(string Customer_Id, string Unit_Id) {
            this.Customer_Id = Customer_Id;
            this.Unit_Id = Unit_Id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMonitorLogNotPackagedCountResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMonitorLogNotPackagedCountResponse", Namespace="http://tempuri.org/", Order=0)]
        public cPos.Admin.Task.MonitorLogServiceReference.GetMonitorLogNotPackagedCountResponseBody Body;
        
        public GetMonitorLogNotPackagedCountResponse() {
        }
        
        public GetMonitorLogNotPackagedCountResponse(cPos.Admin.Task.MonitorLogServiceReference.GetMonitorLogNotPackagedCountResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetMonitorLogNotPackagedCountResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int GetMonitorLogNotPackagedCountResult;
        
        public GetMonitorLogNotPackagedCountResponseBody() {
        }
        
        public GetMonitorLogNotPackagedCountResponseBody(int GetMonitorLogNotPackagedCountResult) {
            this.GetMonitorLogNotPackagedCountResult = GetMonitorLogNotPackagedCountResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMonitorLogListPackagedRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMonitorLogListPackaged", Namespace="http://tempuri.org/", Order=0)]
        public cPos.Admin.Task.MonitorLogServiceReference.GetMonitorLogListPackagedRequestBody Body;
        
        public GetMonitorLogListPackagedRequest() {
        }
        
        public GetMonitorLogListPackagedRequest(cPos.Admin.Task.MonitorLogServiceReference.GetMonitorLogListPackagedRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetMonitorLogListPackagedRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Customer_Id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Unit_Id;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int startRow;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int rowsCount;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string bat_id;
        
        public GetMonitorLogListPackagedRequestBody() {
        }
        
        public GetMonitorLogListPackagedRequestBody(string Customer_Id, string Unit_Id, int startRow, int rowsCount, string bat_id) {
            this.Customer_Id = Customer_Id;
            this.Unit_Id = Unit_Id;
            this.startRow = startRow;
            this.rowsCount = rowsCount;
            this.bat_id = bat_id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMonitorLogListPackagedResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMonitorLogListPackagedResponse", Namespace="http://tempuri.org/", Order=0)]
        public cPos.Admin.Task.MonitorLogServiceReference.GetMonitorLogListPackagedResponseBody Body;
        
        public GetMonitorLogListPackagedResponse() {
        }
        
        public GetMonitorLogListPackagedResponse(cPos.Admin.Task.MonitorLogServiceReference.GetMonitorLogListPackagedResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetMonitorLogListPackagedResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public cPos.Admin.Task.MonitorLogServiceReference.MonitorLogInfo[] GetMonitorLogListPackagedResult;
        
        public GetMonitorLogListPackagedResponseBody() {
        }
        
        public GetMonitorLogListPackagedResponseBody(cPos.Admin.Task.MonitorLogServiceReference.MonitorLogInfo[] GetMonitorLogListPackagedResult) {
            this.GetMonitorLogListPackagedResult = GetMonitorLogListPackagedResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetMonitorLogIfFlagInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetMonitorLogIfFlagInfo", Namespace="http://tempuri.org/", Order=0)]
        public cPos.Admin.Task.MonitorLogServiceReference.SetMonitorLogIfFlagInfoRequestBody Body;
        
        public SetMonitorLogIfFlagInfoRequest() {
        }
        
        public SetMonitorLogIfFlagInfoRequest(cPos.Admin.Task.MonitorLogServiceReference.SetMonitorLogIfFlagInfoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SetMonitorLogIfFlagInfoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Customer_Id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string bat_id;
        
        public SetMonitorLogIfFlagInfoRequestBody() {
        }
        
        public SetMonitorLogIfFlagInfoRequestBody(string Customer_Id, string bat_id) {
            this.Customer_Id = Customer_Id;
            this.bat_id = bat_id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetMonitorLogIfFlagInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetMonitorLogIfFlagInfoResponse", Namespace="http://tempuri.org/", Order=0)]
        public cPos.Admin.Task.MonitorLogServiceReference.SetMonitorLogIfFlagInfoResponseBody Body;
        
        public SetMonitorLogIfFlagInfoResponse() {
        }
        
        public SetMonitorLogIfFlagInfoResponse(cPos.Admin.Task.MonitorLogServiceReference.SetMonitorLogIfFlagInfoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SetMonitorLogIfFlagInfoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool SetMonitorLogIfFlagInfoResult;
        
        public SetMonitorLogIfFlagInfoResponseBody() {
        }
        
        public SetMonitorLogIfFlagInfoResponseBody(bool SetMonitorLogIfFlagInfoResult) {
            this.SetMonitorLogIfFlagInfoResult = SetMonitorLogIfFlagInfoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MonitorLogWebServiceSoapChannel : cPos.Admin.Task.MonitorLogServiceReference.MonitorLogWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MonitorLogWebServiceSoapClient : System.ServiceModel.ClientBase<cPos.Admin.Task.MonitorLogServiceReference.MonitorLogWebServiceSoap>, cPos.Admin.Task.MonitorLogServiceReference.MonitorLogWebServiceSoap {
        
        public MonitorLogWebServiceSoapClient() {
        }
        
        public MonitorLogWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MonitorLogWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MonitorLogWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MonitorLogWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        cPos.Admin.Task.MonitorLogServiceReference.HelloWorldResponse cPos.Admin.Task.MonitorLogServiceReference.MonitorLogWebServiceSoap.HelloWorld(cPos.Admin.Task.MonitorLogServiceReference.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            cPos.Admin.Task.MonitorLogServiceReference.HelloWorldRequest inValue = new cPos.Admin.Task.MonitorLogServiceReference.HelloWorldRequest();
            inValue.Body = new cPos.Admin.Task.MonitorLogServiceReference.HelloWorldRequestBody();
            cPos.Admin.Task.MonitorLogServiceReference.HelloWorldResponse retVal = ((cPos.Admin.Task.MonitorLogServiceReference.MonitorLogWebServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        cPos.Admin.Task.MonitorLogServiceReference.GetMonitorLogNotPackagedCountResponse cPos.Admin.Task.MonitorLogServiceReference.MonitorLogWebServiceSoap.GetMonitorLogNotPackagedCount(cPos.Admin.Task.MonitorLogServiceReference.GetMonitorLogNotPackagedCountRequest request) {
            return base.Channel.GetMonitorLogNotPackagedCount(request);
        }
        
        public int GetMonitorLogNotPackagedCount(string Customer_Id, string Unit_Id) {
            cPos.Admin.Task.MonitorLogServiceReference.GetMonitorLogNotPackagedCountRequest inValue = new cPos.Admin.Task.MonitorLogServiceReference.GetMonitorLogNotPackagedCountRequest();
            inValue.Body = new cPos.Admin.Task.MonitorLogServiceReference.GetMonitorLogNotPackagedCountRequestBody();
            inValue.Body.Customer_Id = Customer_Id;
            inValue.Body.Unit_Id = Unit_Id;
            cPos.Admin.Task.MonitorLogServiceReference.GetMonitorLogNotPackagedCountResponse retVal = ((cPos.Admin.Task.MonitorLogServiceReference.MonitorLogWebServiceSoap)(this)).GetMonitorLogNotPackagedCount(inValue);
            return retVal.Body.GetMonitorLogNotPackagedCountResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        cPos.Admin.Task.MonitorLogServiceReference.GetMonitorLogListPackagedResponse cPos.Admin.Task.MonitorLogServiceReference.MonitorLogWebServiceSoap.GetMonitorLogListPackaged(cPos.Admin.Task.MonitorLogServiceReference.GetMonitorLogListPackagedRequest request) {
            return base.Channel.GetMonitorLogListPackaged(request);
        }
        
        public cPos.Admin.Task.MonitorLogServiceReference.MonitorLogInfo[] GetMonitorLogListPackaged(string Customer_Id, string Unit_Id, int startRow, int rowsCount, string bat_id) {
            cPos.Admin.Task.MonitorLogServiceReference.GetMonitorLogListPackagedRequest inValue = new cPos.Admin.Task.MonitorLogServiceReference.GetMonitorLogListPackagedRequest();
            inValue.Body = new cPos.Admin.Task.MonitorLogServiceReference.GetMonitorLogListPackagedRequestBody();
            inValue.Body.Customer_Id = Customer_Id;
            inValue.Body.Unit_Id = Unit_Id;
            inValue.Body.startRow = startRow;
            inValue.Body.rowsCount = rowsCount;
            inValue.Body.bat_id = bat_id;
            cPos.Admin.Task.MonitorLogServiceReference.GetMonitorLogListPackagedResponse retVal = ((cPos.Admin.Task.MonitorLogServiceReference.MonitorLogWebServiceSoap)(this)).GetMonitorLogListPackaged(inValue);
            return retVal.Body.GetMonitorLogListPackagedResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        cPos.Admin.Task.MonitorLogServiceReference.SetMonitorLogIfFlagInfoResponse cPos.Admin.Task.MonitorLogServiceReference.MonitorLogWebServiceSoap.SetMonitorLogIfFlagInfo(cPos.Admin.Task.MonitorLogServiceReference.SetMonitorLogIfFlagInfoRequest request) {
            return base.Channel.SetMonitorLogIfFlagInfo(request);
        }
        
        public bool SetMonitorLogIfFlagInfo(string Customer_Id, string bat_id) {
            cPos.Admin.Task.MonitorLogServiceReference.SetMonitorLogIfFlagInfoRequest inValue = new cPos.Admin.Task.MonitorLogServiceReference.SetMonitorLogIfFlagInfoRequest();
            inValue.Body = new cPos.Admin.Task.MonitorLogServiceReference.SetMonitorLogIfFlagInfoRequestBody();
            inValue.Body.Customer_Id = Customer_Id;
            inValue.Body.bat_id = bat_id;
            cPos.Admin.Task.MonitorLogServiceReference.SetMonitorLogIfFlagInfoResponse retVal = ((cPos.Admin.Task.MonitorLogServiceReference.MonitorLogWebServiceSoap)(this)).SetMonitorLogIfFlagInfo(inValue);
            return retVal.Body.SetMonitorLogIfFlagInfoResult;
        }
    }
}
