//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cPos.Admin.Task.AdvertiseOrderServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AdvertiseOrderServiceReference.AdvertiseOrderWebServiceSoap")]
    public interface AdvertiseOrderWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        cPos.Admin.Task.AdvertiseOrderServiceReference.HelloWorldResponse HelloWorld(cPos.Admin.Task.AdvertiseOrderServiceReference.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name str from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SetAdvertiseOrderInfos", ReplyAction="*")]
        cPos.Admin.Task.AdvertiseOrderServiceReference.SetAdvertiseOrderInfosResponse SetAdvertiseOrderInfos(cPos.Admin.Task.AdvertiseOrderServiceReference.SetAdvertiseOrderInfosRequest request);
        
        // CODEGEN: Generating message contract since element name str from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SetAdvertiseOrderAdvertiseInfoXML", ReplyAction="*")]
        cPos.Admin.Task.AdvertiseOrderServiceReference.SetAdvertiseOrderAdvertiseInfoXMLResponse SetAdvertiseOrderAdvertiseInfoXML(cPos.Admin.Task.AdvertiseOrderServiceReference.SetAdvertiseOrderAdvertiseInfoXMLRequest request);
        
        // CODEGEN: Generating message contract since element name str from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SetAdvertiseOrderUnitInfoXML", ReplyAction="*")]
        cPos.Admin.Task.AdvertiseOrderServiceReference.SetAdvertiseOrderUnitInfoXMLResponse SetAdvertiseOrderUnitInfoXML(cPos.Admin.Task.AdvertiseOrderServiceReference.SetAdvertiseOrderUnitInfoXMLRequest request);
        
        // CODEGEN: Generating message contract since element name str from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SetAdvertiseInfoXML", ReplyAction="*")]
        cPos.Admin.Task.AdvertiseOrderServiceReference.SetAdvertiseInfoXMLResponse SetAdvertiseInfoXML(cPos.Admin.Task.AdvertiseOrderServiceReference.SetAdvertiseInfoXMLRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public cPos.Admin.Task.AdvertiseOrderServiceReference.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(cPos.Admin.Task.AdvertiseOrderServiceReference.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public cPos.Admin.Task.AdvertiseOrderServiceReference.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(cPos.Admin.Task.AdvertiseOrderServiceReference.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetAdvertiseOrderInfosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetAdvertiseOrderInfos", Namespace="http://tempuri.org/", Order=0)]
        public cPos.Admin.Task.AdvertiseOrderServiceReference.SetAdvertiseOrderInfosRequestBody Body;
        
        public SetAdvertiseOrderInfosRequest() {
        }
        
        public SetAdvertiseOrderInfosRequest(cPos.Admin.Task.AdvertiseOrderServiceReference.SetAdvertiseOrderInfosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SetAdvertiseOrderInfosRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string str;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string customer_id;
        
        public SetAdvertiseOrderInfosRequestBody() {
        }
        
        public SetAdvertiseOrderInfosRequestBody(string str, string customer_id) {
            this.str = str;
            this.customer_id = customer_id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetAdvertiseOrderInfosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetAdvertiseOrderInfosResponse", Namespace="http://tempuri.org/", Order=0)]
        public cPos.Admin.Task.AdvertiseOrderServiceReference.SetAdvertiseOrderInfosResponseBody Body;
        
        public SetAdvertiseOrderInfosResponse() {
        }
        
        public SetAdvertiseOrderInfosResponse(cPos.Admin.Task.AdvertiseOrderServiceReference.SetAdvertiseOrderInfosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SetAdvertiseOrderInfosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool SetAdvertiseOrderInfosResult;
        
        public SetAdvertiseOrderInfosResponseBody() {
        }
        
        public SetAdvertiseOrderInfosResponseBody(bool SetAdvertiseOrderInfosResult) {
            this.SetAdvertiseOrderInfosResult = SetAdvertiseOrderInfosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetAdvertiseOrderAdvertiseInfoXMLRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetAdvertiseOrderAdvertiseInfoXML", Namespace="http://tempuri.org/", Order=0)]
        public cPos.Admin.Task.AdvertiseOrderServiceReference.SetAdvertiseOrderAdvertiseInfoXMLRequestBody Body;
        
        public SetAdvertiseOrderAdvertiseInfoXMLRequest() {
        }
        
        public SetAdvertiseOrderAdvertiseInfoXMLRequest(cPos.Admin.Task.AdvertiseOrderServiceReference.SetAdvertiseOrderAdvertiseInfoXMLRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SetAdvertiseOrderAdvertiseInfoXMLRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string str;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string customer_id;
        
        public SetAdvertiseOrderAdvertiseInfoXMLRequestBody() {
        }
        
        public SetAdvertiseOrderAdvertiseInfoXMLRequestBody(string str, string customer_id) {
            this.str = str;
            this.customer_id = customer_id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetAdvertiseOrderAdvertiseInfoXMLResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetAdvertiseOrderAdvertiseInfoXMLResponse", Namespace="http://tempuri.org/", Order=0)]
        public cPos.Admin.Task.AdvertiseOrderServiceReference.SetAdvertiseOrderAdvertiseInfoXMLResponseBody Body;
        
        public SetAdvertiseOrderAdvertiseInfoXMLResponse() {
        }
        
        public SetAdvertiseOrderAdvertiseInfoXMLResponse(cPos.Admin.Task.AdvertiseOrderServiceReference.SetAdvertiseOrderAdvertiseInfoXMLResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SetAdvertiseOrderAdvertiseInfoXMLResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool SetAdvertiseOrderAdvertiseInfoXMLResult;
        
        public SetAdvertiseOrderAdvertiseInfoXMLResponseBody() {
        }
        
        public SetAdvertiseOrderAdvertiseInfoXMLResponseBody(bool SetAdvertiseOrderAdvertiseInfoXMLResult) {
            this.SetAdvertiseOrderAdvertiseInfoXMLResult = SetAdvertiseOrderAdvertiseInfoXMLResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetAdvertiseOrderUnitInfoXMLRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetAdvertiseOrderUnitInfoXML", Namespace="http://tempuri.org/", Order=0)]
        public cPos.Admin.Task.AdvertiseOrderServiceReference.SetAdvertiseOrderUnitInfoXMLRequestBody Body;
        
        public SetAdvertiseOrderUnitInfoXMLRequest() {
        }
        
        public SetAdvertiseOrderUnitInfoXMLRequest(cPos.Admin.Task.AdvertiseOrderServiceReference.SetAdvertiseOrderUnitInfoXMLRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SetAdvertiseOrderUnitInfoXMLRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string str;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string customer_id;
        
        public SetAdvertiseOrderUnitInfoXMLRequestBody() {
        }
        
        public SetAdvertiseOrderUnitInfoXMLRequestBody(string str, string customer_id) {
            this.str = str;
            this.customer_id = customer_id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetAdvertiseOrderUnitInfoXMLResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetAdvertiseOrderUnitInfoXMLResponse", Namespace="http://tempuri.org/", Order=0)]
        public cPos.Admin.Task.AdvertiseOrderServiceReference.SetAdvertiseOrderUnitInfoXMLResponseBody Body;
        
        public SetAdvertiseOrderUnitInfoXMLResponse() {
        }
        
        public SetAdvertiseOrderUnitInfoXMLResponse(cPos.Admin.Task.AdvertiseOrderServiceReference.SetAdvertiseOrderUnitInfoXMLResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SetAdvertiseOrderUnitInfoXMLResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool SetAdvertiseOrderUnitInfoXMLResult;
        
        public SetAdvertiseOrderUnitInfoXMLResponseBody() {
        }
        
        public SetAdvertiseOrderUnitInfoXMLResponseBody(bool SetAdvertiseOrderUnitInfoXMLResult) {
            this.SetAdvertiseOrderUnitInfoXMLResult = SetAdvertiseOrderUnitInfoXMLResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetAdvertiseInfoXMLRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetAdvertiseInfoXML", Namespace="http://tempuri.org/", Order=0)]
        public cPos.Admin.Task.AdvertiseOrderServiceReference.SetAdvertiseInfoXMLRequestBody Body;
        
        public SetAdvertiseInfoXMLRequest() {
        }
        
        public SetAdvertiseInfoXMLRequest(cPos.Admin.Task.AdvertiseOrderServiceReference.SetAdvertiseInfoXMLRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SetAdvertiseInfoXMLRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string str;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string customer_id;
        
        public SetAdvertiseInfoXMLRequestBody() {
        }
        
        public SetAdvertiseInfoXMLRequestBody(string str, string customer_id) {
            this.str = str;
            this.customer_id = customer_id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetAdvertiseInfoXMLResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetAdvertiseInfoXMLResponse", Namespace="http://tempuri.org/", Order=0)]
        public cPos.Admin.Task.AdvertiseOrderServiceReference.SetAdvertiseInfoXMLResponseBody Body;
        
        public SetAdvertiseInfoXMLResponse() {
        }
        
        public SetAdvertiseInfoXMLResponse(cPos.Admin.Task.AdvertiseOrderServiceReference.SetAdvertiseInfoXMLResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SetAdvertiseInfoXMLResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool SetAdvertiseInfoXMLResult;
        
        public SetAdvertiseInfoXMLResponseBody() {
        }
        
        public SetAdvertiseInfoXMLResponseBody(bool SetAdvertiseInfoXMLResult) {
            this.SetAdvertiseInfoXMLResult = SetAdvertiseInfoXMLResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AdvertiseOrderWebServiceSoapChannel : cPos.Admin.Task.AdvertiseOrderServiceReference.AdvertiseOrderWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AdvertiseOrderWebServiceSoapClient : System.ServiceModel.ClientBase<cPos.Admin.Task.AdvertiseOrderServiceReference.AdvertiseOrderWebServiceSoap>, cPos.Admin.Task.AdvertiseOrderServiceReference.AdvertiseOrderWebServiceSoap {
        
        public AdvertiseOrderWebServiceSoapClient() {
        }
        
        public AdvertiseOrderWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AdvertiseOrderWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdvertiseOrderWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdvertiseOrderWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        cPos.Admin.Task.AdvertiseOrderServiceReference.HelloWorldResponse cPos.Admin.Task.AdvertiseOrderServiceReference.AdvertiseOrderWebServiceSoap.HelloWorld(cPos.Admin.Task.AdvertiseOrderServiceReference.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            cPos.Admin.Task.AdvertiseOrderServiceReference.HelloWorldRequest inValue = new cPos.Admin.Task.AdvertiseOrderServiceReference.HelloWorldRequest();
            inValue.Body = new cPos.Admin.Task.AdvertiseOrderServiceReference.HelloWorldRequestBody();
            cPos.Admin.Task.AdvertiseOrderServiceReference.HelloWorldResponse retVal = ((cPos.Admin.Task.AdvertiseOrderServiceReference.AdvertiseOrderWebServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        cPos.Admin.Task.AdvertiseOrderServiceReference.SetAdvertiseOrderInfosResponse cPos.Admin.Task.AdvertiseOrderServiceReference.AdvertiseOrderWebServiceSoap.SetAdvertiseOrderInfos(cPos.Admin.Task.AdvertiseOrderServiceReference.SetAdvertiseOrderInfosRequest request) {
            return base.Channel.SetAdvertiseOrderInfos(request);
        }
        
        public bool SetAdvertiseOrderInfos(string str, string customer_id) {
            cPos.Admin.Task.AdvertiseOrderServiceReference.SetAdvertiseOrderInfosRequest inValue = new cPos.Admin.Task.AdvertiseOrderServiceReference.SetAdvertiseOrderInfosRequest();
            inValue.Body = new cPos.Admin.Task.AdvertiseOrderServiceReference.SetAdvertiseOrderInfosRequestBody();
            inValue.Body.str = str;
            inValue.Body.customer_id = customer_id;
            cPos.Admin.Task.AdvertiseOrderServiceReference.SetAdvertiseOrderInfosResponse retVal = ((cPos.Admin.Task.AdvertiseOrderServiceReference.AdvertiseOrderWebServiceSoap)(this)).SetAdvertiseOrderInfos(inValue);
            return retVal.Body.SetAdvertiseOrderInfosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        cPos.Admin.Task.AdvertiseOrderServiceReference.SetAdvertiseOrderAdvertiseInfoXMLResponse cPos.Admin.Task.AdvertiseOrderServiceReference.AdvertiseOrderWebServiceSoap.SetAdvertiseOrderAdvertiseInfoXML(cPos.Admin.Task.AdvertiseOrderServiceReference.SetAdvertiseOrderAdvertiseInfoXMLRequest request) {
            return base.Channel.SetAdvertiseOrderAdvertiseInfoXML(request);
        }
        
        public bool SetAdvertiseOrderAdvertiseInfoXML(string str, string customer_id) {
            cPos.Admin.Task.AdvertiseOrderServiceReference.SetAdvertiseOrderAdvertiseInfoXMLRequest inValue = new cPos.Admin.Task.AdvertiseOrderServiceReference.SetAdvertiseOrderAdvertiseInfoXMLRequest();
            inValue.Body = new cPos.Admin.Task.AdvertiseOrderServiceReference.SetAdvertiseOrderAdvertiseInfoXMLRequestBody();
            inValue.Body.str = str;
            inValue.Body.customer_id = customer_id;
            cPos.Admin.Task.AdvertiseOrderServiceReference.SetAdvertiseOrderAdvertiseInfoXMLResponse retVal = ((cPos.Admin.Task.AdvertiseOrderServiceReference.AdvertiseOrderWebServiceSoap)(this)).SetAdvertiseOrderAdvertiseInfoXML(inValue);
            return retVal.Body.SetAdvertiseOrderAdvertiseInfoXMLResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        cPos.Admin.Task.AdvertiseOrderServiceReference.SetAdvertiseOrderUnitInfoXMLResponse cPos.Admin.Task.AdvertiseOrderServiceReference.AdvertiseOrderWebServiceSoap.SetAdvertiseOrderUnitInfoXML(cPos.Admin.Task.AdvertiseOrderServiceReference.SetAdvertiseOrderUnitInfoXMLRequest request) {
            return base.Channel.SetAdvertiseOrderUnitInfoXML(request);
        }
        
        public bool SetAdvertiseOrderUnitInfoXML(string str, string customer_id) {
            cPos.Admin.Task.AdvertiseOrderServiceReference.SetAdvertiseOrderUnitInfoXMLRequest inValue = new cPos.Admin.Task.AdvertiseOrderServiceReference.SetAdvertiseOrderUnitInfoXMLRequest();
            inValue.Body = new cPos.Admin.Task.AdvertiseOrderServiceReference.SetAdvertiseOrderUnitInfoXMLRequestBody();
            inValue.Body.str = str;
            inValue.Body.customer_id = customer_id;
            cPos.Admin.Task.AdvertiseOrderServiceReference.SetAdvertiseOrderUnitInfoXMLResponse retVal = ((cPos.Admin.Task.AdvertiseOrderServiceReference.AdvertiseOrderWebServiceSoap)(this)).SetAdvertiseOrderUnitInfoXML(inValue);
            return retVal.Body.SetAdvertiseOrderUnitInfoXMLResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        cPos.Admin.Task.AdvertiseOrderServiceReference.SetAdvertiseInfoXMLResponse cPos.Admin.Task.AdvertiseOrderServiceReference.AdvertiseOrderWebServiceSoap.SetAdvertiseInfoXML(cPos.Admin.Task.AdvertiseOrderServiceReference.SetAdvertiseInfoXMLRequest request) {
            return base.Channel.SetAdvertiseInfoXML(request);
        }
        
        public bool SetAdvertiseInfoXML(string str, string customer_id) {
            cPos.Admin.Task.AdvertiseOrderServiceReference.SetAdvertiseInfoXMLRequest inValue = new cPos.Admin.Task.AdvertiseOrderServiceReference.SetAdvertiseInfoXMLRequest();
            inValue.Body = new cPos.Admin.Task.AdvertiseOrderServiceReference.SetAdvertiseInfoXMLRequestBody();
            inValue.Body.str = str;
            inValue.Body.customer_id = customer_id;
            cPos.Admin.Task.AdvertiseOrderServiceReference.SetAdvertiseInfoXMLResponse retVal = ((cPos.Admin.Task.AdvertiseOrderServiceReference.AdvertiseOrderWebServiceSoap)(this)).SetAdvertiseInfoXML(inValue);
            return retVal.Body.SetAdvertiseInfoXMLResult;
        }
    }
}
