//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cPos.Dex.WsService.AP.APBasicServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="APBasicServiceReference.BasicServiceSoap")]
    public interface BasicServiceSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        cPos.Dex.WsService.AP.APBasicServiceReference.HelloWorldResponse HelloWorld(cPos.Dex.WsService.AP.APBasicServiceReference.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name barcode from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetItemInfoByBarcode", ReplyAction="*")]
        cPos.Dex.WsService.AP.APBasicServiceReference.GetItemInfoByBarcodeResponse GetItemInfoByBarcode(cPos.Dex.WsService.AP.APBasicServiceReference.GetItemInfoByBarcodeRequest request);
        
        // CODEGEN: Generating message contract since element name userId from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUserUnitRelations", ReplyAction="*")]
        cPos.Dex.WsService.AP.APBasicServiceReference.GetUserUnitRelationsResponse GetUserUnitRelations(cPos.Dex.WsService.AP.APBasicServiceReference.GetUserUnitRelationsRequest request);
        
        // CODEGEN: Generating message contract since element name userId from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ApplyCustomerAndUnit", ReplyAction="*")]
        cPos.Dex.WsService.AP.APBasicServiceReference.ApplyCustomerAndUnitResponse ApplyCustomerAndUnit(cPos.Dex.WsService.AP.APBasicServiceReference.ApplyCustomerAndUnitRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public cPos.Dex.WsService.AP.APBasicServiceReference.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(cPos.Dex.WsService.AP.APBasicServiceReference.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public cPos.Dex.WsService.AP.APBasicServiceReference.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(cPos.Dex.WsService.AP.APBasicServiceReference.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetItemInfoByBarcodeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetItemInfoByBarcode", Namespace="http://tempuri.org/", Order=0)]
        public cPos.Dex.WsService.AP.APBasicServiceReference.GetItemInfoByBarcodeRequestBody Body;
        
        public GetItemInfoByBarcodeRequest() {
        }
        
        public GetItemInfoByBarcodeRequest(cPos.Dex.WsService.AP.APBasicServiceReference.GetItemInfoByBarcodeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetItemInfoByBarcodeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string barcode;
        
        public GetItemInfoByBarcodeRequestBody() {
        }
        
        public GetItemInfoByBarcodeRequestBody(string barcode) {
            this.barcode = barcode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetItemInfoByBarcodeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetItemInfoByBarcodeResponse", Namespace="http://tempuri.org/", Order=0)]
        public cPos.Dex.WsService.AP.APBasicServiceReference.GetItemInfoByBarcodeResponseBody Body;
        
        public GetItemInfoByBarcodeResponse() {
        }
        
        public GetItemInfoByBarcodeResponse(cPos.Dex.WsService.AP.APBasicServiceReference.GetItemInfoByBarcodeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetItemInfoByBarcodeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetItemInfoByBarcodeResult;
        
        public GetItemInfoByBarcodeResponseBody() {
        }
        
        public GetItemInfoByBarcodeResponseBody(string GetItemInfoByBarcodeResult) {
            this.GetItemInfoByBarcodeResult = GetItemInfoByBarcodeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserUnitRelationsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserUnitRelations", Namespace="http://tempuri.org/", Order=0)]
        public cPos.Dex.WsService.AP.APBasicServiceReference.GetUserUnitRelationsRequestBody Body;
        
        public GetUserUnitRelationsRequest() {
        }
        
        public GetUserUnitRelationsRequest(cPos.Dex.WsService.AP.APBasicServiceReference.GetUserUnitRelationsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUserUnitRelationsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string type;
        
        public GetUserUnitRelationsRequestBody() {
        }
        
        public GetUserUnitRelationsRequestBody(string userId, string type) {
            this.userId = userId;
            this.type = type;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserUnitRelationsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserUnitRelationsResponse", Namespace="http://tempuri.org/", Order=0)]
        public cPos.Dex.WsService.AP.APBasicServiceReference.GetUserUnitRelationsResponseBody Body;
        
        public GetUserUnitRelationsResponse() {
        }
        
        public GetUserUnitRelationsResponse(cPos.Dex.WsService.AP.APBasicServiceReference.GetUserUnitRelationsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUserUnitRelationsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetUserUnitRelationsResult;
        
        public GetUserUnitRelationsResponseBody() {
        }
        
        public GetUserUnitRelationsResponseBody(string GetUserUnitRelationsResult) {
            this.GetUserUnitRelationsResult = GetUserUnitRelationsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ApplyCustomerAndUnitRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ApplyCustomerAndUnit", Namespace="http://tempuri.org/", Order=0)]
        public cPos.Dex.WsService.AP.APBasicServiceReference.ApplyCustomerAndUnitRequestBody Body;
        
        public ApplyCustomerAndUnitRequest() {
        }
        
        public ApplyCustomerAndUnitRequest(cPos.Dex.WsService.AP.APBasicServiceReference.ApplyCustomerAndUnitRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ApplyCustomerAndUnitRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string customerInfo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string unitInfo;
        
        public ApplyCustomerAndUnitRequestBody() {
        }
        
        public ApplyCustomerAndUnitRequestBody(string userId, string customerInfo, string unitInfo) {
            this.userId = userId;
            this.customerInfo = customerInfo;
            this.unitInfo = unitInfo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ApplyCustomerAndUnitResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ApplyCustomerAndUnitResponse", Namespace="http://tempuri.org/", Order=0)]
        public cPos.Dex.WsService.AP.APBasicServiceReference.ApplyCustomerAndUnitResponseBody Body;
        
        public ApplyCustomerAndUnitResponse() {
        }
        
        public ApplyCustomerAndUnitResponse(cPos.Dex.WsService.AP.APBasicServiceReference.ApplyCustomerAndUnitResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ApplyCustomerAndUnitResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ApplyCustomerAndUnitResult;
        
        public ApplyCustomerAndUnitResponseBody() {
        }
        
        public ApplyCustomerAndUnitResponseBody(string ApplyCustomerAndUnitResult) {
            this.ApplyCustomerAndUnitResult = ApplyCustomerAndUnitResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BasicServiceSoapChannel : cPos.Dex.WsService.AP.APBasicServiceReference.BasicServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BasicServiceSoapClient : System.ServiceModel.ClientBase<cPos.Dex.WsService.AP.APBasicServiceReference.BasicServiceSoap>, cPos.Dex.WsService.AP.APBasicServiceReference.BasicServiceSoap {
        
        public BasicServiceSoapClient() {
        }
        
        public BasicServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BasicServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BasicServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BasicServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        cPos.Dex.WsService.AP.APBasicServiceReference.HelloWorldResponse cPos.Dex.WsService.AP.APBasicServiceReference.BasicServiceSoap.HelloWorld(cPos.Dex.WsService.AP.APBasicServiceReference.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            cPos.Dex.WsService.AP.APBasicServiceReference.HelloWorldRequest inValue = new cPos.Dex.WsService.AP.APBasicServiceReference.HelloWorldRequest();
            inValue.Body = new cPos.Dex.WsService.AP.APBasicServiceReference.HelloWorldRequestBody();
            cPos.Dex.WsService.AP.APBasicServiceReference.HelloWorldResponse retVal = ((cPos.Dex.WsService.AP.APBasicServiceReference.BasicServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        cPos.Dex.WsService.AP.APBasicServiceReference.GetItemInfoByBarcodeResponse cPos.Dex.WsService.AP.APBasicServiceReference.BasicServiceSoap.GetItemInfoByBarcode(cPos.Dex.WsService.AP.APBasicServiceReference.GetItemInfoByBarcodeRequest request) {
            return base.Channel.GetItemInfoByBarcode(request);
        }
        
        public string GetItemInfoByBarcode(string barcode) {
            cPos.Dex.WsService.AP.APBasicServiceReference.GetItemInfoByBarcodeRequest inValue = new cPos.Dex.WsService.AP.APBasicServiceReference.GetItemInfoByBarcodeRequest();
            inValue.Body = new cPos.Dex.WsService.AP.APBasicServiceReference.GetItemInfoByBarcodeRequestBody();
            inValue.Body.barcode = barcode;
            cPos.Dex.WsService.AP.APBasicServiceReference.GetItemInfoByBarcodeResponse retVal = ((cPos.Dex.WsService.AP.APBasicServiceReference.BasicServiceSoap)(this)).GetItemInfoByBarcode(inValue);
            return retVal.Body.GetItemInfoByBarcodeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        cPos.Dex.WsService.AP.APBasicServiceReference.GetUserUnitRelationsResponse cPos.Dex.WsService.AP.APBasicServiceReference.BasicServiceSoap.GetUserUnitRelations(cPos.Dex.WsService.AP.APBasicServiceReference.GetUserUnitRelationsRequest request) {
            return base.Channel.GetUserUnitRelations(request);
        }
        
        public string GetUserUnitRelations(string userId, string type) {
            cPos.Dex.WsService.AP.APBasicServiceReference.GetUserUnitRelationsRequest inValue = new cPos.Dex.WsService.AP.APBasicServiceReference.GetUserUnitRelationsRequest();
            inValue.Body = new cPos.Dex.WsService.AP.APBasicServiceReference.GetUserUnitRelationsRequestBody();
            inValue.Body.userId = userId;
            inValue.Body.type = type;
            cPos.Dex.WsService.AP.APBasicServiceReference.GetUserUnitRelationsResponse retVal = ((cPos.Dex.WsService.AP.APBasicServiceReference.BasicServiceSoap)(this)).GetUserUnitRelations(inValue);
            return retVal.Body.GetUserUnitRelationsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        cPos.Dex.WsService.AP.APBasicServiceReference.ApplyCustomerAndUnitResponse cPos.Dex.WsService.AP.APBasicServiceReference.BasicServiceSoap.ApplyCustomerAndUnit(cPos.Dex.WsService.AP.APBasicServiceReference.ApplyCustomerAndUnitRequest request) {
            return base.Channel.ApplyCustomerAndUnit(request);
        }
        
        public string ApplyCustomerAndUnit(string userId, string customerInfo, string unitInfo) {
            cPos.Dex.WsService.AP.APBasicServiceReference.ApplyCustomerAndUnitRequest inValue = new cPos.Dex.WsService.AP.APBasicServiceReference.ApplyCustomerAndUnitRequest();
            inValue.Body = new cPos.Dex.WsService.AP.APBasicServiceReference.ApplyCustomerAndUnitRequestBody();
            inValue.Body.userId = userId;
            inValue.Body.customerInfo = customerInfo;
            inValue.Body.unitInfo = unitInfo;
            cPos.Dex.WsService.AP.APBasicServiceReference.ApplyCustomerAndUnitResponse retVal = ((cPos.Dex.WsService.AP.APBasicServiceReference.BasicServiceSoap)(this)).ApplyCustomerAndUnit(inValue);
            return retVal.Body.ApplyCustomerAndUnitResult;
        }
    }
}
