//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cPos.Admin.Task.PosInoutServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InoutInfo", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class InoutInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string order_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string order_noField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string order_type_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string order_reason_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string red_flagField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ref_order_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ref_order_noField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string warehouse_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string order_dateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string request_dateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string complete_dateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string create_unit_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string unit_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string unit_nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string related_unit_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string related_unit_codeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string pos_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string shift_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sales_userField;
        
        private decimal total_amountField;
        
        private decimal discount_rateField;
        
        private decimal actual_amountField;
        
        private decimal receive_pointsField;
        
        private decimal pay_pointsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string pay_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string payment_nameField;
        
        private int print_timesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string carrier_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string remarkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string statusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string status_descField;
        
        private decimal total_qtyField;
        
        private decimal total_retailField;
        
        private decimal keep_the_changeField;
        
        private decimal wiping_zeroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string vip_noField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string create_timeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string create_user_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string approve_timeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string approve_user_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string send_timeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string send_user_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string accpect_timeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string accpect_user_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string modify_timeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string modify_user_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string create_unit_nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string create_user_nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string approve_user_nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string send_user_nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string accpect_user_nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string modify_user_nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string order_type_codeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string order_type_nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string order_reason_codeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string order_reason_nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sales_unit_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string purchase_unit_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sales_unit_nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string purchase_unit_nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string warehouse_nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BillKindCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string data_from_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string data_from_nameField;
        
        private int Row_NoField;
        
        private int ICountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string operateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string if_flagField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string customer_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string bat_idField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string order_id {
            get {
                return this.order_idField;
            }
            set {
                if ((object.ReferenceEquals(this.order_idField, value) != true)) {
                    this.order_idField = value;
                    this.RaisePropertyChanged("order_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string order_no {
            get {
                return this.order_noField;
            }
            set {
                if ((object.ReferenceEquals(this.order_noField, value) != true)) {
                    this.order_noField = value;
                    this.RaisePropertyChanged("order_no");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string order_type_id {
            get {
                return this.order_type_idField;
            }
            set {
                if ((object.ReferenceEquals(this.order_type_idField, value) != true)) {
                    this.order_type_idField = value;
                    this.RaisePropertyChanged("order_type_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string order_reason_id {
            get {
                return this.order_reason_idField;
            }
            set {
                if ((object.ReferenceEquals(this.order_reason_idField, value) != true)) {
                    this.order_reason_idField = value;
                    this.RaisePropertyChanged("order_reason_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string red_flag {
            get {
                return this.red_flagField;
            }
            set {
                if ((object.ReferenceEquals(this.red_flagField, value) != true)) {
                    this.red_flagField = value;
                    this.RaisePropertyChanged("red_flag");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string ref_order_id {
            get {
                return this.ref_order_idField;
            }
            set {
                if ((object.ReferenceEquals(this.ref_order_idField, value) != true)) {
                    this.ref_order_idField = value;
                    this.RaisePropertyChanged("ref_order_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string ref_order_no {
            get {
                return this.ref_order_noField;
            }
            set {
                if ((object.ReferenceEquals(this.ref_order_noField, value) != true)) {
                    this.ref_order_noField = value;
                    this.RaisePropertyChanged("ref_order_no");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string warehouse_id {
            get {
                return this.warehouse_idField;
            }
            set {
                if ((object.ReferenceEquals(this.warehouse_idField, value) != true)) {
                    this.warehouse_idField = value;
                    this.RaisePropertyChanged("warehouse_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string order_date {
            get {
                return this.order_dateField;
            }
            set {
                if ((object.ReferenceEquals(this.order_dateField, value) != true)) {
                    this.order_dateField = value;
                    this.RaisePropertyChanged("order_date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string request_date {
            get {
                return this.request_dateField;
            }
            set {
                if ((object.ReferenceEquals(this.request_dateField, value) != true)) {
                    this.request_dateField = value;
                    this.RaisePropertyChanged("request_date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string complete_date {
            get {
                return this.complete_dateField;
            }
            set {
                if ((object.ReferenceEquals(this.complete_dateField, value) != true)) {
                    this.complete_dateField = value;
                    this.RaisePropertyChanged("complete_date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string create_unit_id {
            get {
                return this.create_unit_idField;
            }
            set {
                if ((object.ReferenceEquals(this.create_unit_idField, value) != true)) {
                    this.create_unit_idField = value;
                    this.RaisePropertyChanged("create_unit_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string unit_id {
            get {
                return this.unit_idField;
            }
            set {
                if ((object.ReferenceEquals(this.unit_idField, value) != true)) {
                    this.unit_idField = value;
                    this.RaisePropertyChanged("unit_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string unit_name {
            get {
                return this.unit_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.unit_nameField, value) != true)) {
                    this.unit_nameField = value;
                    this.RaisePropertyChanged("unit_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string related_unit_id {
            get {
                return this.related_unit_idField;
            }
            set {
                if ((object.ReferenceEquals(this.related_unit_idField, value) != true)) {
                    this.related_unit_idField = value;
                    this.RaisePropertyChanged("related_unit_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string related_unit_code {
            get {
                return this.related_unit_codeField;
            }
            set {
                if ((object.ReferenceEquals(this.related_unit_codeField, value) != true)) {
                    this.related_unit_codeField = value;
                    this.RaisePropertyChanged("related_unit_code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public string pos_id {
            get {
                return this.pos_idField;
            }
            set {
                if ((object.ReferenceEquals(this.pos_idField, value) != true)) {
                    this.pos_idField = value;
                    this.RaisePropertyChanged("pos_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=17)]
        public string shift_id {
            get {
                return this.shift_idField;
            }
            set {
                if ((object.ReferenceEquals(this.shift_idField, value) != true)) {
                    this.shift_idField = value;
                    this.RaisePropertyChanged("shift_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=18)]
        public string sales_user {
            get {
                return this.sales_userField;
            }
            set {
                if ((object.ReferenceEquals(this.sales_userField, value) != true)) {
                    this.sales_userField = value;
                    this.RaisePropertyChanged("sales_user");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=19)]
        public decimal total_amount {
            get {
                return this.total_amountField;
            }
            set {
                if ((this.total_amountField.Equals(value) != true)) {
                    this.total_amountField = value;
                    this.RaisePropertyChanged("total_amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=20)]
        public decimal discount_rate {
            get {
                return this.discount_rateField;
            }
            set {
                if ((this.discount_rateField.Equals(value) != true)) {
                    this.discount_rateField = value;
                    this.RaisePropertyChanged("discount_rate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=21)]
        public decimal actual_amount {
            get {
                return this.actual_amountField;
            }
            set {
                if ((this.actual_amountField.Equals(value) != true)) {
                    this.actual_amountField = value;
                    this.RaisePropertyChanged("actual_amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=22)]
        public decimal receive_points {
            get {
                return this.receive_pointsField;
            }
            set {
                if ((this.receive_pointsField.Equals(value) != true)) {
                    this.receive_pointsField = value;
                    this.RaisePropertyChanged("receive_points");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=23)]
        public decimal pay_points {
            get {
                return this.pay_pointsField;
            }
            set {
                if ((this.pay_pointsField.Equals(value) != true)) {
                    this.pay_pointsField = value;
                    this.RaisePropertyChanged("pay_points");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=24)]
        public string pay_id {
            get {
                return this.pay_idField;
            }
            set {
                if ((object.ReferenceEquals(this.pay_idField, value) != true)) {
                    this.pay_idField = value;
                    this.RaisePropertyChanged("pay_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=25)]
        public string payment_name {
            get {
                return this.payment_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.payment_nameField, value) != true)) {
                    this.payment_nameField = value;
                    this.RaisePropertyChanged("payment_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=26)]
        public int print_times {
            get {
                return this.print_timesField;
            }
            set {
                if ((this.print_timesField.Equals(value) != true)) {
                    this.print_timesField = value;
                    this.RaisePropertyChanged("print_times");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=27)]
        public string carrier_id {
            get {
                return this.carrier_idField;
            }
            set {
                if ((object.ReferenceEquals(this.carrier_idField, value) != true)) {
                    this.carrier_idField = value;
                    this.RaisePropertyChanged("carrier_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=28)]
        public string remark {
            get {
                return this.remarkField;
            }
            set {
                if ((object.ReferenceEquals(this.remarkField, value) != true)) {
                    this.remarkField = value;
                    this.RaisePropertyChanged("remark");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=29)]
        public string status {
            get {
                return this.statusField;
            }
            set {
                if ((object.ReferenceEquals(this.statusField, value) != true)) {
                    this.statusField = value;
                    this.RaisePropertyChanged("status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=30)]
        public string status_desc {
            get {
                return this.status_descField;
            }
            set {
                if ((object.ReferenceEquals(this.status_descField, value) != true)) {
                    this.status_descField = value;
                    this.RaisePropertyChanged("status_desc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=31)]
        public decimal total_qty {
            get {
                return this.total_qtyField;
            }
            set {
                if ((this.total_qtyField.Equals(value) != true)) {
                    this.total_qtyField = value;
                    this.RaisePropertyChanged("total_qty");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=32)]
        public decimal total_retail {
            get {
                return this.total_retailField;
            }
            set {
                if ((this.total_retailField.Equals(value) != true)) {
                    this.total_retailField = value;
                    this.RaisePropertyChanged("total_retail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=33)]
        public decimal keep_the_change {
            get {
                return this.keep_the_changeField;
            }
            set {
                if ((this.keep_the_changeField.Equals(value) != true)) {
                    this.keep_the_changeField = value;
                    this.RaisePropertyChanged("keep_the_change");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=34)]
        public decimal wiping_zero {
            get {
                return this.wiping_zeroField;
            }
            set {
                if ((this.wiping_zeroField.Equals(value) != true)) {
                    this.wiping_zeroField = value;
                    this.RaisePropertyChanged("wiping_zero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=35)]
        public string vip_no {
            get {
                return this.vip_noField;
            }
            set {
                if ((object.ReferenceEquals(this.vip_noField, value) != true)) {
                    this.vip_noField = value;
                    this.RaisePropertyChanged("vip_no");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=36)]
        public string create_time {
            get {
                return this.create_timeField;
            }
            set {
                if ((object.ReferenceEquals(this.create_timeField, value) != true)) {
                    this.create_timeField = value;
                    this.RaisePropertyChanged("create_time");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=37)]
        public string create_user_id {
            get {
                return this.create_user_idField;
            }
            set {
                if ((object.ReferenceEquals(this.create_user_idField, value) != true)) {
                    this.create_user_idField = value;
                    this.RaisePropertyChanged("create_user_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=38)]
        public string approve_time {
            get {
                return this.approve_timeField;
            }
            set {
                if ((object.ReferenceEquals(this.approve_timeField, value) != true)) {
                    this.approve_timeField = value;
                    this.RaisePropertyChanged("approve_time");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=39)]
        public string approve_user_id {
            get {
                return this.approve_user_idField;
            }
            set {
                if ((object.ReferenceEquals(this.approve_user_idField, value) != true)) {
                    this.approve_user_idField = value;
                    this.RaisePropertyChanged("approve_user_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=40)]
        public string send_time {
            get {
                return this.send_timeField;
            }
            set {
                if ((object.ReferenceEquals(this.send_timeField, value) != true)) {
                    this.send_timeField = value;
                    this.RaisePropertyChanged("send_time");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=41)]
        public string send_user_id {
            get {
                return this.send_user_idField;
            }
            set {
                if ((object.ReferenceEquals(this.send_user_idField, value) != true)) {
                    this.send_user_idField = value;
                    this.RaisePropertyChanged("send_user_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=42)]
        public string accpect_time {
            get {
                return this.accpect_timeField;
            }
            set {
                if ((object.ReferenceEquals(this.accpect_timeField, value) != true)) {
                    this.accpect_timeField = value;
                    this.RaisePropertyChanged("accpect_time");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=43)]
        public string accpect_user_id {
            get {
                return this.accpect_user_idField;
            }
            set {
                if ((object.ReferenceEquals(this.accpect_user_idField, value) != true)) {
                    this.accpect_user_idField = value;
                    this.RaisePropertyChanged("accpect_user_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=44)]
        public string modify_time {
            get {
                return this.modify_timeField;
            }
            set {
                if ((object.ReferenceEquals(this.modify_timeField, value) != true)) {
                    this.modify_timeField = value;
                    this.RaisePropertyChanged("modify_time");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=45)]
        public string modify_user_id {
            get {
                return this.modify_user_idField;
            }
            set {
                if ((object.ReferenceEquals(this.modify_user_idField, value) != true)) {
                    this.modify_user_idField = value;
                    this.RaisePropertyChanged("modify_user_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=46)]
        public string create_unit_name {
            get {
                return this.create_unit_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.create_unit_nameField, value) != true)) {
                    this.create_unit_nameField = value;
                    this.RaisePropertyChanged("create_unit_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=47)]
        public string create_user_name {
            get {
                return this.create_user_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.create_user_nameField, value) != true)) {
                    this.create_user_nameField = value;
                    this.RaisePropertyChanged("create_user_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=48)]
        public string approve_user_name {
            get {
                return this.approve_user_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.approve_user_nameField, value) != true)) {
                    this.approve_user_nameField = value;
                    this.RaisePropertyChanged("approve_user_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=49)]
        public string send_user_name {
            get {
                return this.send_user_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.send_user_nameField, value) != true)) {
                    this.send_user_nameField = value;
                    this.RaisePropertyChanged("send_user_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=50)]
        public string accpect_user_name {
            get {
                return this.accpect_user_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.accpect_user_nameField, value) != true)) {
                    this.accpect_user_nameField = value;
                    this.RaisePropertyChanged("accpect_user_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=51)]
        public string modify_user_name {
            get {
                return this.modify_user_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.modify_user_nameField, value) != true)) {
                    this.modify_user_nameField = value;
                    this.RaisePropertyChanged("modify_user_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=52)]
        public string order_type_code {
            get {
                return this.order_type_codeField;
            }
            set {
                if ((object.ReferenceEquals(this.order_type_codeField, value) != true)) {
                    this.order_type_codeField = value;
                    this.RaisePropertyChanged("order_type_code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=53)]
        public string order_type_name {
            get {
                return this.order_type_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.order_type_nameField, value) != true)) {
                    this.order_type_nameField = value;
                    this.RaisePropertyChanged("order_type_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=54)]
        public string order_reason_code {
            get {
                return this.order_reason_codeField;
            }
            set {
                if ((object.ReferenceEquals(this.order_reason_codeField, value) != true)) {
                    this.order_reason_codeField = value;
                    this.RaisePropertyChanged("order_reason_code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=55)]
        public string order_reason_name {
            get {
                return this.order_reason_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.order_reason_nameField, value) != true)) {
                    this.order_reason_nameField = value;
                    this.RaisePropertyChanged("order_reason_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=56)]
        public string sales_unit_id {
            get {
                return this.sales_unit_idField;
            }
            set {
                if ((object.ReferenceEquals(this.sales_unit_idField, value) != true)) {
                    this.sales_unit_idField = value;
                    this.RaisePropertyChanged("sales_unit_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=57)]
        public string purchase_unit_id {
            get {
                return this.purchase_unit_idField;
            }
            set {
                if ((object.ReferenceEquals(this.purchase_unit_idField, value) != true)) {
                    this.purchase_unit_idField = value;
                    this.RaisePropertyChanged("purchase_unit_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=58)]
        public string sales_unit_name {
            get {
                return this.sales_unit_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.sales_unit_nameField, value) != true)) {
                    this.sales_unit_nameField = value;
                    this.RaisePropertyChanged("sales_unit_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=59)]
        public string purchase_unit_name {
            get {
                return this.purchase_unit_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.purchase_unit_nameField, value) != true)) {
                    this.purchase_unit_nameField = value;
                    this.RaisePropertyChanged("purchase_unit_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=60)]
        public string warehouse_name {
            get {
                return this.warehouse_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.warehouse_nameField, value) != true)) {
                    this.warehouse_nameField = value;
                    this.RaisePropertyChanged("warehouse_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=61)]
        public string BillKindCode {
            get {
                return this.BillKindCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.BillKindCodeField, value) != true)) {
                    this.BillKindCodeField = value;
                    this.RaisePropertyChanged("BillKindCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=62)]
        public string data_from_id {
            get {
                return this.data_from_idField;
            }
            set {
                if ((object.ReferenceEquals(this.data_from_idField, value) != true)) {
                    this.data_from_idField = value;
                    this.RaisePropertyChanged("data_from_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=63)]
        public string data_from_name {
            get {
                return this.data_from_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.data_from_nameField, value) != true)) {
                    this.data_from_nameField = value;
                    this.RaisePropertyChanged("data_from_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=64)]
        public int Row_No {
            get {
                return this.Row_NoField;
            }
            set {
                if ((this.Row_NoField.Equals(value) != true)) {
                    this.Row_NoField = value;
                    this.RaisePropertyChanged("Row_No");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=65)]
        public int ICount {
            get {
                return this.ICountField;
            }
            set {
                if ((this.ICountField.Equals(value) != true)) {
                    this.ICountField = value;
                    this.RaisePropertyChanged("ICount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=66)]
        public string operate {
            get {
                return this.operateField;
            }
            set {
                if ((object.ReferenceEquals(this.operateField, value) != true)) {
                    this.operateField = value;
                    this.RaisePropertyChanged("operate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=67)]
        public string if_flag {
            get {
                return this.if_flagField;
            }
            set {
                if ((object.ReferenceEquals(this.if_flagField, value) != true)) {
                    this.if_flagField = value;
                    this.RaisePropertyChanged("if_flag");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=68)]
        public string customer_id {
            get {
                return this.customer_idField;
            }
            set {
                if ((object.ReferenceEquals(this.customer_idField, value) != true)) {
                    this.customer_idField = value;
                    this.RaisePropertyChanged("customer_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=69)]
        public string bat_id {
            get {
                return this.bat_idField;
            }
            set {
                if ((object.ReferenceEquals(this.bat_idField, value) != true)) {
                    this.bat_idField = value;
                    this.RaisePropertyChanged("bat_id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InoutDetailInfo", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class InoutDetailInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string order_detail_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string order_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ref_order_detail_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sku_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string unit_idField;
        
        private decimal order_qtyField;
        
        private decimal enter_qtyField;
        
        private decimal enter_priceField;
        
        private decimal enter_amountField;
        
        private decimal std_priceField;
        
        private decimal order_discount_rateField;
        
        private decimal discount_rateField;
        
        private decimal retail_priceField;
        
        private decimal retail_amountField;
        
        private decimal plan_priceField;
        
        private decimal receive_pointsField;
        
        private decimal pay_pointsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string remarkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string pos_order_codeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string order_detail_statusField;
        
        private int display_indexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string create_timeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string create_user_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string modify_timeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string modify_user_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ref_order_idField;
        
        private int if_flagField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string item_codeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string item_nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string prop_1_detail_nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string prop_2_detail_nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string prop_3_detail_nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string prop_4_detail_nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string prop_5_detail_nameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string order_detail_id {
            get {
                return this.order_detail_idField;
            }
            set {
                if ((object.ReferenceEquals(this.order_detail_idField, value) != true)) {
                    this.order_detail_idField = value;
                    this.RaisePropertyChanged("order_detail_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string order_id {
            get {
                return this.order_idField;
            }
            set {
                if ((object.ReferenceEquals(this.order_idField, value) != true)) {
                    this.order_idField = value;
                    this.RaisePropertyChanged("order_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ref_order_detail_id {
            get {
                return this.ref_order_detail_idField;
            }
            set {
                if ((object.ReferenceEquals(this.ref_order_detail_idField, value) != true)) {
                    this.ref_order_detail_idField = value;
                    this.RaisePropertyChanged("ref_order_detail_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string sku_id {
            get {
                return this.sku_idField;
            }
            set {
                if ((object.ReferenceEquals(this.sku_idField, value) != true)) {
                    this.sku_idField = value;
                    this.RaisePropertyChanged("sku_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string unit_id {
            get {
                return this.unit_idField;
            }
            set {
                if ((object.ReferenceEquals(this.unit_idField, value) != true)) {
                    this.unit_idField = value;
                    this.RaisePropertyChanged("unit_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public decimal order_qty {
            get {
                return this.order_qtyField;
            }
            set {
                if ((this.order_qtyField.Equals(value) != true)) {
                    this.order_qtyField = value;
                    this.RaisePropertyChanged("order_qty");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public decimal enter_qty {
            get {
                return this.enter_qtyField;
            }
            set {
                if ((this.enter_qtyField.Equals(value) != true)) {
                    this.enter_qtyField = value;
                    this.RaisePropertyChanged("enter_qty");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public decimal enter_price {
            get {
                return this.enter_priceField;
            }
            set {
                if ((this.enter_priceField.Equals(value) != true)) {
                    this.enter_priceField = value;
                    this.RaisePropertyChanged("enter_price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public decimal enter_amount {
            get {
                return this.enter_amountField;
            }
            set {
                if ((this.enter_amountField.Equals(value) != true)) {
                    this.enter_amountField = value;
                    this.RaisePropertyChanged("enter_amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public decimal std_price {
            get {
                return this.std_priceField;
            }
            set {
                if ((this.std_priceField.Equals(value) != true)) {
                    this.std_priceField = value;
                    this.RaisePropertyChanged("std_price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public decimal order_discount_rate {
            get {
                return this.order_discount_rateField;
            }
            set {
                if ((this.order_discount_rateField.Equals(value) != true)) {
                    this.order_discount_rateField = value;
                    this.RaisePropertyChanged("order_discount_rate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=11)]
        public decimal discount_rate {
            get {
                return this.discount_rateField;
            }
            set {
                if ((this.discount_rateField.Equals(value) != true)) {
                    this.discount_rateField = value;
                    this.RaisePropertyChanged("discount_rate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=12)]
        public decimal retail_price {
            get {
                return this.retail_priceField;
            }
            set {
                if ((this.retail_priceField.Equals(value) != true)) {
                    this.retail_priceField = value;
                    this.RaisePropertyChanged("retail_price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=13)]
        public decimal retail_amount {
            get {
                return this.retail_amountField;
            }
            set {
                if ((this.retail_amountField.Equals(value) != true)) {
                    this.retail_amountField = value;
                    this.RaisePropertyChanged("retail_amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=14)]
        public decimal plan_price {
            get {
                return this.plan_priceField;
            }
            set {
                if ((this.plan_priceField.Equals(value) != true)) {
                    this.plan_priceField = value;
                    this.RaisePropertyChanged("plan_price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=15)]
        public decimal receive_points {
            get {
                return this.receive_pointsField;
            }
            set {
                if ((this.receive_pointsField.Equals(value) != true)) {
                    this.receive_pointsField = value;
                    this.RaisePropertyChanged("receive_points");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=16)]
        public decimal pay_points {
            get {
                return this.pay_pointsField;
            }
            set {
                if ((this.pay_pointsField.Equals(value) != true)) {
                    this.pay_pointsField = value;
                    this.RaisePropertyChanged("pay_points");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=17)]
        public string remark {
            get {
                return this.remarkField;
            }
            set {
                if ((object.ReferenceEquals(this.remarkField, value) != true)) {
                    this.remarkField = value;
                    this.RaisePropertyChanged("remark");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=18)]
        public string pos_order_code {
            get {
                return this.pos_order_codeField;
            }
            set {
                if ((object.ReferenceEquals(this.pos_order_codeField, value) != true)) {
                    this.pos_order_codeField = value;
                    this.RaisePropertyChanged("pos_order_code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=19)]
        public string order_detail_status {
            get {
                return this.order_detail_statusField;
            }
            set {
                if ((object.ReferenceEquals(this.order_detail_statusField, value) != true)) {
                    this.order_detail_statusField = value;
                    this.RaisePropertyChanged("order_detail_status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=20)]
        public int display_index {
            get {
                return this.display_indexField;
            }
            set {
                if ((this.display_indexField.Equals(value) != true)) {
                    this.display_indexField = value;
                    this.RaisePropertyChanged("display_index");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=21)]
        public string create_time {
            get {
                return this.create_timeField;
            }
            set {
                if ((object.ReferenceEquals(this.create_timeField, value) != true)) {
                    this.create_timeField = value;
                    this.RaisePropertyChanged("create_time");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=22)]
        public string create_user_id {
            get {
                return this.create_user_idField;
            }
            set {
                if ((object.ReferenceEquals(this.create_user_idField, value) != true)) {
                    this.create_user_idField = value;
                    this.RaisePropertyChanged("create_user_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=23)]
        public string modify_time {
            get {
                return this.modify_timeField;
            }
            set {
                if ((object.ReferenceEquals(this.modify_timeField, value) != true)) {
                    this.modify_timeField = value;
                    this.RaisePropertyChanged("modify_time");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=24)]
        public string modify_user_id {
            get {
                return this.modify_user_idField;
            }
            set {
                if ((object.ReferenceEquals(this.modify_user_idField, value) != true)) {
                    this.modify_user_idField = value;
                    this.RaisePropertyChanged("modify_user_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=25)]
        public string ref_order_id {
            get {
                return this.ref_order_idField;
            }
            set {
                if ((object.ReferenceEquals(this.ref_order_idField, value) != true)) {
                    this.ref_order_idField = value;
                    this.RaisePropertyChanged("ref_order_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=26)]
        public int if_flag {
            get {
                return this.if_flagField;
            }
            set {
                if ((this.if_flagField.Equals(value) != true)) {
                    this.if_flagField = value;
                    this.RaisePropertyChanged("if_flag");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=27)]
        public string item_code {
            get {
                return this.item_codeField;
            }
            set {
                if ((object.ReferenceEquals(this.item_codeField, value) != true)) {
                    this.item_codeField = value;
                    this.RaisePropertyChanged("item_code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=28)]
        public string item_name {
            get {
                return this.item_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.item_nameField, value) != true)) {
                    this.item_nameField = value;
                    this.RaisePropertyChanged("item_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=29)]
        public string prop_1_detail_name {
            get {
                return this.prop_1_detail_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.prop_1_detail_nameField, value) != true)) {
                    this.prop_1_detail_nameField = value;
                    this.RaisePropertyChanged("prop_1_detail_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=30)]
        public string prop_2_detail_name {
            get {
                return this.prop_2_detail_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.prop_2_detail_nameField, value) != true)) {
                    this.prop_2_detail_nameField = value;
                    this.RaisePropertyChanged("prop_2_detail_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=31)]
        public string prop_3_detail_name {
            get {
                return this.prop_3_detail_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.prop_3_detail_nameField, value) != true)) {
                    this.prop_3_detail_nameField = value;
                    this.RaisePropertyChanged("prop_3_detail_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=32)]
        public string prop_4_detail_name {
            get {
                return this.prop_4_detail_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.prop_4_detail_nameField, value) != true)) {
                    this.prop_4_detail_nameField = value;
                    this.RaisePropertyChanged("prop_4_detail_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=33)]
        public string prop_5_detail_name {
            get {
                return this.prop_5_detail_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.prop_5_detail_nameField, value) != true)) {
                    this.prop_5_detail_nameField = value;
                    this.RaisePropertyChanged("prop_5_detail_name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PosInoutServiceReference.PosInoutWebServiceSoap")]
    public interface PosInoutWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        cPos.Admin.Task.PosInoutServiceReference.HelloWorldResponse HelloWorld(cPos.Admin.Task.PosInoutServiceReference.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name Customer_Id from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPosInoutNotPackagedCount", ReplyAction="*")]
        cPos.Admin.Task.PosInoutServiceReference.GetPosInoutNotPackagedCountResponse GetPosInoutNotPackagedCount(cPos.Admin.Task.PosInoutServiceReference.GetPosInoutNotPackagedCountRequest request);
        
        // CODEGEN: Generating message contract since element name Customer_Id from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPosInoutListPackaged", ReplyAction="*")]
        cPos.Admin.Task.PosInoutServiceReference.GetPosInoutListPackagedResponse GetPosInoutListPackaged(cPos.Admin.Task.PosInoutServiceReference.GetPosInoutListPackagedRequest request);
        
        // CODEGEN: Generating message contract since element name Customer_Id from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPosInoutDetailListPackaged", ReplyAction="*")]
        cPos.Admin.Task.PosInoutServiceReference.GetPosInoutDetailListPackagedResponse GetPosInoutDetailListPackaged(cPos.Admin.Task.PosInoutServiceReference.GetPosInoutDetailListPackagedRequest request);
        
        // CODEGEN: Generating message contract since element name Customer_Id from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SetPosInoutIfFlagInfo", ReplyAction="*")]
        cPos.Admin.Task.PosInoutServiceReference.SetPosInoutIfFlagInfoResponse SetPosInoutIfFlagInfo(cPos.Admin.Task.PosInoutServiceReference.SetPosInoutIfFlagInfoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public cPos.Admin.Task.PosInoutServiceReference.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(cPos.Admin.Task.PosInoutServiceReference.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public cPos.Admin.Task.PosInoutServiceReference.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(cPos.Admin.Task.PosInoutServiceReference.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPosInoutNotPackagedCountRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPosInoutNotPackagedCount", Namespace="http://tempuri.org/", Order=0)]
        public cPos.Admin.Task.PosInoutServiceReference.GetPosInoutNotPackagedCountRequestBody Body;
        
        public GetPosInoutNotPackagedCountRequest() {
        }
        
        public GetPosInoutNotPackagedCountRequest(cPos.Admin.Task.PosInoutServiceReference.GetPosInoutNotPackagedCountRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetPosInoutNotPackagedCountRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Customer_Id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Unit_Id;
        
        public GetPosInoutNotPackagedCountRequestBody() {
        }
        
        public GetPosInoutNotPackagedCountRequestBody(string Customer_Id, string Unit_Id) {
            this.Customer_Id = Customer_Id;
            this.Unit_Id = Unit_Id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPosInoutNotPackagedCountResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPosInoutNotPackagedCountResponse", Namespace="http://tempuri.org/", Order=0)]
        public cPos.Admin.Task.PosInoutServiceReference.GetPosInoutNotPackagedCountResponseBody Body;
        
        public GetPosInoutNotPackagedCountResponse() {
        }
        
        public GetPosInoutNotPackagedCountResponse(cPos.Admin.Task.PosInoutServiceReference.GetPosInoutNotPackagedCountResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetPosInoutNotPackagedCountResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int GetPosInoutNotPackagedCountResult;
        
        public GetPosInoutNotPackagedCountResponseBody() {
        }
        
        public GetPosInoutNotPackagedCountResponseBody(int GetPosInoutNotPackagedCountResult) {
            this.GetPosInoutNotPackagedCountResult = GetPosInoutNotPackagedCountResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPosInoutListPackagedRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPosInoutListPackaged", Namespace="http://tempuri.org/", Order=0)]
        public cPos.Admin.Task.PosInoutServiceReference.GetPosInoutListPackagedRequestBody Body;
        
        public GetPosInoutListPackagedRequest() {
        }
        
        public GetPosInoutListPackagedRequest(cPos.Admin.Task.PosInoutServiceReference.GetPosInoutListPackagedRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetPosInoutListPackagedRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Customer_Id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Unit_Id;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int startRow;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int rowsCount;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string bat_id;
        
        public GetPosInoutListPackagedRequestBody() {
        }
        
        public GetPosInoutListPackagedRequestBody(string Customer_Id, string Unit_Id, int startRow, int rowsCount, string bat_id) {
            this.Customer_Id = Customer_Id;
            this.Unit_Id = Unit_Id;
            this.startRow = startRow;
            this.rowsCount = rowsCount;
            this.bat_id = bat_id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPosInoutListPackagedResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPosInoutListPackagedResponse", Namespace="http://tempuri.org/", Order=0)]
        public cPos.Admin.Task.PosInoutServiceReference.GetPosInoutListPackagedResponseBody Body;
        
        public GetPosInoutListPackagedResponse() {
        }
        
        public GetPosInoutListPackagedResponse(cPos.Admin.Task.PosInoutServiceReference.GetPosInoutListPackagedResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetPosInoutListPackagedResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public cPos.Admin.Task.PosInoutServiceReference.InoutInfo[] GetPosInoutListPackagedResult;
        
        public GetPosInoutListPackagedResponseBody() {
        }
        
        public GetPosInoutListPackagedResponseBody(cPos.Admin.Task.PosInoutServiceReference.InoutInfo[] GetPosInoutListPackagedResult) {
            this.GetPosInoutListPackagedResult = GetPosInoutListPackagedResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPosInoutDetailListPackagedRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPosInoutDetailListPackaged", Namespace="http://tempuri.org/", Order=0)]
        public cPos.Admin.Task.PosInoutServiceReference.GetPosInoutDetailListPackagedRequestBody Body;
        
        public GetPosInoutDetailListPackagedRequest() {
        }
        
        public GetPosInoutDetailListPackagedRequest(cPos.Admin.Task.PosInoutServiceReference.GetPosInoutDetailListPackagedRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetPosInoutDetailListPackagedRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Customer_Id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Unit_Id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public cPos.Admin.Task.PosInoutServiceReference.InoutInfo[] inoutInfoList;
        
        public GetPosInoutDetailListPackagedRequestBody() {
        }
        
        public GetPosInoutDetailListPackagedRequestBody(string Customer_Id, string Unit_Id, cPos.Admin.Task.PosInoutServiceReference.InoutInfo[] inoutInfoList) {
            this.Customer_Id = Customer_Id;
            this.Unit_Id = Unit_Id;
            this.inoutInfoList = inoutInfoList;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPosInoutDetailListPackagedResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPosInoutDetailListPackagedResponse", Namespace="http://tempuri.org/", Order=0)]
        public cPos.Admin.Task.PosInoutServiceReference.GetPosInoutDetailListPackagedResponseBody Body;
        
        public GetPosInoutDetailListPackagedResponse() {
        }
        
        public GetPosInoutDetailListPackagedResponse(cPos.Admin.Task.PosInoutServiceReference.GetPosInoutDetailListPackagedResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetPosInoutDetailListPackagedResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public cPos.Admin.Task.PosInoutServiceReference.InoutDetailInfo[] GetPosInoutDetailListPackagedResult;
        
        public GetPosInoutDetailListPackagedResponseBody() {
        }
        
        public GetPosInoutDetailListPackagedResponseBody(cPos.Admin.Task.PosInoutServiceReference.InoutDetailInfo[] GetPosInoutDetailListPackagedResult) {
            this.GetPosInoutDetailListPackagedResult = GetPosInoutDetailListPackagedResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetPosInoutIfFlagInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetPosInoutIfFlagInfo", Namespace="http://tempuri.org/", Order=0)]
        public cPos.Admin.Task.PosInoutServiceReference.SetPosInoutIfFlagInfoRequestBody Body;
        
        public SetPosInoutIfFlagInfoRequest() {
        }
        
        public SetPosInoutIfFlagInfoRequest(cPos.Admin.Task.PosInoutServiceReference.SetPosInoutIfFlagInfoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SetPosInoutIfFlagInfoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Customer_Id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string bat_id;
        
        public SetPosInoutIfFlagInfoRequestBody() {
        }
        
        public SetPosInoutIfFlagInfoRequestBody(string Customer_Id, string bat_id) {
            this.Customer_Id = Customer_Id;
            this.bat_id = bat_id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetPosInoutIfFlagInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetPosInoutIfFlagInfoResponse", Namespace="http://tempuri.org/", Order=0)]
        public cPos.Admin.Task.PosInoutServiceReference.SetPosInoutIfFlagInfoResponseBody Body;
        
        public SetPosInoutIfFlagInfoResponse() {
        }
        
        public SetPosInoutIfFlagInfoResponse(cPos.Admin.Task.PosInoutServiceReference.SetPosInoutIfFlagInfoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SetPosInoutIfFlagInfoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool SetPosInoutIfFlagInfoResult;
        
        public SetPosInoutIfFlagInfoResponseBody() {
        }
        
        public SetPosInoutIfFlagInfoResponseBody(bool SetPosInoutIfFlagInfoResult) {
            this.SetPosInoutIfFlagInfoResult = SetPosInoutIfFlagInfoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PosInoutWebServiceSoapChannel : cPos.Admin.Task.PosInoutServiceReference.PosInoutWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PosInoutWebServiceSoapClient : System.ServiceModel.ClientBase<cPos.Admin.Task.PosInoutServiceReference.PosInoutWebServiceSoap>, cPos.Admin.Task.PosInoutServiceReference.PosInoutWebServiceSoap {
        
        public PosInoutWebServiceSoapClient() {
        }
        
        public PosInoutWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PosInoutWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PosInoutWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PosInoutWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        cPos.Admin.Task.PosInoutServiceReference.HelloWorldResponse cPos.Admin.Task.PosInoutServiceReference.PosInoutWebServiceSoap.HelloWorld(cPos.Admin.Task.PosInoutServiceReference.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            cPos.Admin.Task.PosInoutServiceReference.HelloWorldRequest inValue = new cPos.Admin.Task.PosInoutServiceReference.HelloWorldRequest();
            inValue.Body = new cPos.Admin.Task.PosInoutServiceReference.HelloWorldRequestBody();
            cPos.Admin.Task.PosInoutServiceReference.HelloWorldResponse retVal = ((cPos.Admin.Task.PosInoutServiceReference.PosInoutWebServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        cPos.Admin.Task.PosInoutServiceReference.GetPosInoutNotPackagedCountResponse cPos.Admin.Task.PosInoutServiceReference.PosInoutWebServiceSoap.GetPosInoutNotPackagedCount(cPos.Admin.Task.PosInoutServiceReference.GetPosInoutNotPackagedCountRequest request) {
            return base.Channel.GetPosInoutNotPackagedCount(request);
        }
        
        public int GetPosInoutNotPackagedCount(string Customer_Id, string Unit_Id) {
            cPos.Admin.Task.PosInoutServiceReference.GetPosInoutNotPackagedCountRequest inValue = new cPos.Admin.Task.PosInoutServiceReference.GetPosInoutNotPackagedCountRequest();
            inValue.Body = new cPos.Admin.Task.PosInoutServiceReference.GetPosInoutNotPackagedCountRequestBody();
            inValue.Body.Customer_Id = Customer_Id;
            inValue.Body.Unit_Id = Unit_Id;
            cPos.Admin.Task.PosInoutServiceReference.GetPosInoutNotPackagedCountResponse retVal = ((cPos.Admin.Task.PosInoutServiceReference.PosInoutWebServiceSoap)(this)).GetPosInoutNotPackagedCount(inValue);
            return retVal.Body.GetPosInoutNotPackagedCountResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        cPos.Admin.Task.PosInoutServiceReference.GetPosInoutListPackagedResponse cPos.Admin.Task.PosInoutServiceReference.PosInoutWebServiceSoap.GetPosInoutListPackaged(cPos.Admin.Task.PosInoutServiceReference.GetPosInoutListPackagedRequest request) {
            return base.Channel.GetPosInoutListPackaged(request);
        }
        
        public cPos.Admin.Task.PosInoutServiceReference.InoutInfo[] GetPosInoutListPackaged(string Customer_Id, string Unit_Id, int startRow, int rowsCount, string bat_id) {
            cPos.Admin.Task.PosInoutServiceReference.GetPosInoutListPackagedRequest inValue = new cPos.Admin.Task.PosInoutServiceReference.GetPosInoutListPackagedRequest();
            inValue.Body = new cPos.Admin.Task.PosInoutServiceReference.GetPosInoutListPackagedRequestBody();
            inValue.Body.Customer_Id = Customer_Id;
            inValue.Body.Unit_Id = Unit_Id;
            inValue.Body.startRow = startRow;
            inValue.Body.rowsCount = rowsCount;
            inValue.Body.bat_id = bat_id;
            cPos.Admin.Task.PosInoutServiceReference.GetPosInoutListPackagedResponse retVal = ((cPos.Admin.Task.PosInoutServiceReference.PosInoutWebServiceSoap)(this)).GetPosInoutListPackaged(inValue);
            return retVal.Body.GetPosInoutListPackagedResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        cPos.Admin.Task.PosInoutServiceReference.GetPosInoutDetailListPackagedResponse cPos.Admin.Task.PosInoutServiceReference.PosInoutWebServiceSoap.GetPosInoutDetailListPackaged(cPos.Admin.Task.PosInoutServiceReference.GetPosInoutDetailListPackagedRequest request) {
            return base.Channel.GetPosInoutDetailListPackaged(request);
        }
        
        public cPos.Admin.Task.PosInoutServiceReference.InoutDetailInfo[] GetPosInoutDetailListPackaged(string Customer_Id, string Unit_Id, cPos.Admin.Task.PosInoutServiceReference.InoutInfo[] inoutInfoList) {
            cPos.Admin.Task.PosInoutServiceReference.GetPosInoutDetailListPackagedRequest inValue = new cPos.Admin.Task.PosInoutServiceReference.GetPosInoutDetailListPackagedRequest();
            inValue.Body = new cPos.Admin.Task.PosInoutServiceReference.GetPosInoutDetailListPackagedRequestBody();
            inValue.Body.Customer_Id = Customer_Id;
            inValue.Body.Unit_Id = Unit_Id;
            inValue.Body.inoutInfoList = inoutInfoList;
            cPos.Admin.Task.PosInoutServiceReference.GetPosInoutDetailListPackagedResponse retVal = ((cPos.Admin.Task.PosInoutServiceReference.PosInoutWebServiceSoap)(this)).GetPosInoutDetailListPackaged(inValue);
            return retVal.Body.GetPosInoutDetailListPackagedResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        cPos.Admin.Task.PosInoutServiceReference.SetPosInoutIfFlagInfoResponse cPos.Admin.Task.PosInoutServiceReference.PosInoutWebServiceSoap.SetPosInoutIfFlagInfo(cPos.Admin.Task.PosInoutServiceReference.SetPosInoutIfFlagInfoRequest request) {
            return base.Channel.SetPosInoutIfFlagInfo(request);
        }
        
        public bool SetPosInoutIfFlagInfo(string Customer_Id, string bat_id) {
            cPos.Admin.Task.PosInoutServiceReference.SetPosInoutIfFlagInfoRequest inValue = new cPos.Admin.Task.PosInoutServiceReference.SetPosInoutIfFlagInfoRequest();
            inValue.Body = new cPos.Admin.Task.PosInoutServiceReference.SetPosInoutIfFlagInfoRequestBody();
            inValue.Body.Customer_Id = Customer_Id;
            inValue.Body.bat_id = bat_id;
            cPos.Admin.Task.PosInoutServiceReference.SetPosInoutIfFlagInfoResponse retVal = ((cPos.Admin.Task.PosInoutServiceReference.PosInoutWebServiceSoap)(this)).SetPosInoutIfFlagInfo(inValue);
            return retVal.Body.SetPosInoutIfFlagInfoResult;
        }
    }
}
